### ISSUE TITLE
Unexpected token: name (protected)

### ISSUE THREAD

**Issue by deenice** [rc1021/serialize-json#3]
When using your repo in my project, compiling js returns me this error.
I think you should change your variable name to something else than `protected` because it is not allowed.

Here the full error message:
```
ERROR in /dist/index.js from Terser
Unexpected token: name (protected) [./node_modules/form-serialize-json/serialize-json.js:96,0][/dist/index.js:17562,30]
```

**Comment by rc1021** [comment]
thanks. 
It is already merged.
