### ISSUE TITLE
Terser Unexpected token: name (protected)

### ISSUE THREAD

**Issue by hhalim** [rc1021/serialize-json#6]
I'm getting an error when running npm run build.
error
js/chunk-25833661.84f22283.js from Terser
Unexpected token: name (protected) [./node_modules/form-serialize-json/serialize-json.js:96,0]

I think this is solved in this commit https://github.com/rc1021/serialize-json/commit/68220eeb40953cb2047018dfdc0e526fa9fbfac4

Do you have a timeline for a new release?
Thanks!

**Comment by rc1021** [comment]
@hhalim v1.0 is released.
